name: twicon
description: Free icons of Taiwan. The package contains a set of icons by a Japanese and an English designer, that coverts the themes like sights, products, traffic, etc, in Taiwan.
version: 0.2.0
homepage: https://github.com/zonble/twicon

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: "Taiwan icon"
      fonts:
        - asset: packages/twicon/fonts/twicon.otf
